config/routes.rb
CodeHunterDashboard::Application.routes.draw do
  root :to => "reports#top"

  get "/login" => redirect("/auth/github"), :as => :login

  resources :reports, :only => [:index, :show, :create] do
    collection do
      get :stats
      get :latest
      get :top
    end

    resources :warnings, :only => [] do
      collection do
        get ":author" => :author, :as => :author
      end
    end
  end

  resources :warnings, :only => :show

  resource :user, :only => :show

  controller :sessions do
    get "auth/:provider/callback" => :create
    get "auth/failure"            => :failure
    delete "logout"               => :destroy
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :brakeman_count, :rails_best_practices_count, :pendaxes_count

  has_many :warnings, :order => "modified_at DESC"

  scope :descending, lambda {
    order("created_at DESC")
  }

  delegate :brakeman, :rails_best_practices, :to => :warnings

  def self.create_with_warnings(warning_attributes_set)
    create.tap do |report|
      warning_attributes_set.each do |attributes|
        report.warnings.create(attributes)
      end
    end
  end

  def self.latest
    descending.first or raise ActiveRecord::RecordNotFound
  end

  def brakeman
    warnings.brakeman
  end

  def time
    created_at.strftime("%Y-%m-%d %H:%M")
  end

  def added_warnings
    hash = previous_warnings.group_by(&:sha1)
    warnings.reject {|warning| hash[warning.sha1] }
  end

  def removed_warnings
    hash = warnings.group_by(&:sha1)
    previous_warnings.reject {|warning| hash[warning.sha1] }
  end

  private

  def previous
    self.class.where("created_at < ?", created_at).descending.first
  end

  def previous_warnings
    previous.try(:warnings) || []
  end
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/settings.yml"
  namespace Rails.env

  def self.github_api_endpoint
    "https://#{github.host}/api/v3"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :emails, :image, :nickname, :provider, :token, :uid

  validates :emails, :nickname, :provider, :token, :presence => true
  validates :uid, :presence => true, :uniqueness => { :scope => :provider }

  class << self
    def from_omniauth(auth)
      where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
    end

    private

    def create_from_omniauth(auth)
      user = new(
        :image    => auth["info"]["image"],
        :nickname => auth["info"]["nickname"],
        :token    => auth["credentials"]["token"],
        :provider => auth["provider"],
        :uid      => auth["uid"],
      )
      user.fetch_emails!
      user.tap(&:save)
    end
  end

  def emails
    self[:emails].try(:split, ",")
  end

  def emails=(emails)
    self[:emails] = emails.join(",")
  end

  def fetch_emails!
    self.emails = fetch_emails
  end

  def fetch_emails
    client.users.emails.all.map {|hash| hash.email }
  end

  private

  def client
    @client ||= Github.new(:oauth_token => token, :endpoint => Settings.github_api_endpoint)
  end
end

app/models/warning.rb
class Warning < ActiveRecord::Base
  SERVICE_TYPE_TABLE = {
    "rails_best_practices" => "Bad Smell",
    "pendaxes"             => "Pending",
    "brakeman"             => "Security",
  }

  SERVICE_SEVERITY_TABLE = {
    "rails_best_practices" => "default",
    "pendaxes"             => "warning",
    "brakeman"             => "important",
  }

  attr_accessible :author, :email, :line, :message, :modified_at, :path, :service, :sha1, :url

  belongs_to :report

  after_create :increment_counter_cache

  scope :recently_modified, lambda { order("modified_at DESC") }

  scope :modified_in_this_week, lambda { where(:modified_at => (Time.now - 7.days) .. Time.now) }

  def save(*)
    self[:modified_at] = Time.at(modified_at + 9.hours) if modified_at.is_a? Fixnum
    super
  end

  def type
    SERVICE_TYPE_TABLE[service]
  end

  def severity
    SERVICE_SEVERITY_TABLE[service]
  end

  def github_file_path
    if Settings.github.repository
      [
        "https:/",
        Settings.github.host,
        Settings.github.repository,
        "blob",
        sha1,
        Settings.github.rails_root,
        %<#{path}#{"#L#{line}" if line}>
      ].compact.join("/")
    end
  end

  def github_commit_path
    if Settings.github.repository
      [
        "https:/",
        Settings.github.host,
        Settings.github.repository,
        "commit",
        sha1,
      ].join("/")
    end
  end

  def path_with_line
    [path, line].compact.join(":")
  end

  private

  def increment_counter_cache
    attribute = "#{service}_count"
    report.increment!(attribute) if report.respond_to?(attribute)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login

  helper_method :current_user, :logged_in?, :login_path

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to login_path unless logged_in?
  end

  def require_latest_report
    @report = Report.latest
  end

  def login_path
    "#{root_path}auth/github"
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  protect_from_forgery

  skip_before_filter :require_login, :only => :create
  before_filter :require_warnings_as_json, only: :create
  before_filter :require_latest_report, :only => [:top, :stats, :latest]

  def index
    @reports = Report.descending.limit(20)
  end

  def show
    @report = Report.find(params[:id])
  end

  def top
  end

  def stats
    @reports = Report.descending.limit(100)
  end

  def latest
    @report = Report.latest
    render :show
  end

  def create
    Report.create_with_warnings(@warnings)
    head :ok
  end

  private

  def require_warnings_as_json
    @warnings = JSON.parse(params[:warnings])
  rescue JSON::ParserError, TypeError
    head :bad_request
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to user_path
  end

  def destroy
    session[:user_id] = nil
    render :logout
  end

  def failure
    head 401
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_latest_report

  def show
    @warnings          = @report.warnings.where(:email => current_user.emails)
    @brakeman_warnings = @warnings.select {|warning| warning.service == "brakeman" }
    @rbp_warnings      = @warnings.select {|warning| warning.service == "rails_best_practices" }
    @pendaxes_warnings = @warnings.select {|warning| warning.service == "pendaxes" }
  end
end

app/controllers/warnings_controller.rb
class WarningsController < ApplicationController
  def show
    @warning = Warning.find(params[:id])
  end

  def author
    @report = Report.find(params[:report_id])
    @warnings = @report.warnings.where(:author => params[:author])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def absolute_css_class_names
    %W[#{controller_name}_controller #{action_name}_action]
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def to_count_csv(reports, counter_column_name)
    rows = []
    rows << "Time,Count"
    rows += reports.map {|report| "#{report.created_at},#{report.send(counter_column_name)}" }
    rows.join("\n")
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title CodeHunter
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body class=absolute_css_class_names
    header
      .logo
        = link_to root_path do
          h1
            i.icon-dashboard
            | Code Hunter
          h2
            ' Metrics dashboard to hunt out weak spots
      ul.links
        li= link_to user_path, :title => "You" do
          - if current_user.try(:image)
            = image_tag current_user.image, :size => "25x25"
          - else
            i.icon-user
        li= link_to latest_reports_path, :title => "Latest" do
          i.icon-file-alt
        li= link_to stats_reports_path, :title => "Stats" do
          i.icon-bar-chart
        li= link_to reports_path, :title => "Reports" do
          i.icon-list
        - if logged_in?
          li= link_to logout_path, :title => "Logout", :method => :delete do
            i.icon-signout

    .main
      = yield

app/views/reports/_chart.html.slim
.chart.section class=service
  h3
    i.icon-bar-chart
    = service.humanize
  .csv data-json=to_count_csv(reports, "#{service}_count").to_json
  .graph style="width: 100%"

app/views/reports/_recent_warnings.html.slim
.section
  h3
    i.icon-cloud-upload
    | Recently added
  table.warnings.table
    thead
      tr
        th commit
        th author
        th message
    tbody
      - report.warnings.limit(20).each do |warning|
        tr
          td= warning.modified_at.to_date
          td= link_to warning.author, author_report_warnings_path(:report_id => report.id, :author => warning.author)
          td= link_to warning.message, warning

app/views/reports/index.html.slim
.section
  h3
    i.icon-list
    | Reports
  table.table
    thead
      tr
        th Ceated at
        th Brakeman
        th Rails Best Practices
        th Pendaxes
    tbody
      - @reports.each do |report|
        tr
          td= link_to report.created_at, report
          td= report.brakeman_count
          td= report.rails_best_practices_count
          td= report.pendaxes_count

app/views/reports/show.html.slim
.section
  h3
    i.icon-file-alt
    | Report##{@report.id} status
  .counts
    .count
      .value
        = @report.brakeman_count
      p Brakeman
    .count
      .value
        = @report.rails_best_practices_count
      p Rails Best Practices
    .count
      .value
        = @report.pendaxes_count
      p Pendaxes

.section
  div
    h3
      i.icon-plus
      | Added
    ul
      - @report.added_warnings.each do |warning|
        li
          = link_to warning.message, warning
  .div
    h3
      i.icon-minus
      | Removed
    ul
      - @report.removed_warnings.each do |warning|
        li
          = link_to warning.message, warning

.section
  h3
    i.icon-list
    | Details
  = render "warnings/warnings", :report => @report, :warnings => @report.warnings

app/views/reports/stats.html.slim
= render "chart", :service => "brakeman", :reports => @reports
= render "chart", :service => "rails_best_practices", :reports => @reports
= render "chart", :service => "pendaxes", :reports => @reports

app/views/reports/top.html.slim
.section
  h3
    i.icon-eye-open
    | Current status
  .counts
    .count
      .value
        = @report.brakeman_count || 0
      p Brakeman
    .count
      .value
        = @report.rails_best_practices_count || 0
      p Rails Best Practices
    .count
      .value
        = @report.pendaxes_count || 0
      p Pendaxes

.section
  h3
    i.icon-cloud-upload
    | Latest
  table.warnings.table
    thead
      tr
        th Commit
        th Author
        th Type
        th Message
    tbody
      - @report.warnings.limit(10).each do |warning|
        tr
          td.date= warning.modified_at.to_date
          td.author= link_to warning.author, author_report_warnings_path(:report_id => @report.id, :author => warning.author)
          td.type
            .label class="label-#{warning.severity}"
              = warning.type
          td.message= link_to warning.message, warning
  p
    = link_to latest_reports_path do
      i.icon-double-angle-right
      | Show more detail

.section
  h3
    i.icon-question-sign
    | What is this site?
  p
    ' We continuously monitor the metrics of your rails application.
    br
    ' If there are any bad code smells or possible security weakness,
    ' a note will be posted here.
    br
    ' Let's try to improve your code quality!
  ul.links
    li= link_to user_path do
      i.icon-user
      | Your status
    li= link_to latest_reports_path do
      i.icon-file-alt
      | Latest report
    li= link_to stats_reports_path do
      i.icon-bar-chart
      | Statistics
    li= link_to reports_path do
      i.icon-list
      | All reports

app/views/users/_user.html.slim
h3
  i.icon-user
  | Your status

.summary.section
  table.table.table-bordered.table-striped.report
    tr
      th brakeman count
      td= @brakeman_warnings.count
    tr
      th rails_best_practices count
      td= @rbp_warnings.count

.warnings.section
  = render "warnings/warnings", :warnings => @warnings, :report => @report

app/views/users/show.html.slim
.section
  h3
    - if current_user.image
      = image_tag current_user.image, :size => "25x25"
    - else
      i.icon-user
    | #{current_user.nickname}'s status
  .counts
    .count
      .value
        = @brakeman_warnings.count
      p Brakeman
    .count
      .value
        = @rbp_warnings.count
      p Rails Best Practices
    .count
      .value
        = @pendaxes_warnings.count
      p Pendaxes

.section
  h3
    i.icon-list
    | Details
  = render "warnings/warnings", :warnings => @warnings, :report => @report

app/views/warnings/_warnings.html.slim
.tabbed_warnings
  ul.nav.nav-tabs
    li.active= link_to "all", ""
    li= link_to "brakeman", ""
    li= link_to "rails_best_practices", ""
    li= link_to "pendaxes", ""
  table.table.warnings
    thead
      tr
        th Commit
        th Author
        th Type
        th Message
    tbody
      - warnings.each do |warning|
        tr.all class=warning.service
          td.date= warning.modified_at.to_date
          td.author= link_to warning.author, author_report_warnings_path(:report_id => report.id, :author => warning.author)
          td
            .label class="label-#{warning.severity}"
              = warning.type
          td.message= link_to warning.message, warning

app/views/warnings/author.html.slim
.section
  h3
    i.icon-user
    = params[:author]
    | 's status
  .counts
    .count
      .value
        = @warnings.select {|warning| warning.service == "brakeman" }.count
      p Brakeman
    .count
      .value
        = @warnings.select {|warning| warning.service == "rails_best_practices" }.count
      p Rails Best Practices
    .count
      .value
        = @warnings.select {|warning| warning.service == "pendaxes" }.count
      p Pendaxes

.warnings.section
  h3
    i.icon-list
    | Details
  = render "warnings/warnings", :warnings => @warnings, :report => @report

app/views/warnings/show.html.slim
.section.warning
  h3
    i.icon-stethoscope
    | Warning Detail
  table.table
    tbody
      tr.message
        td colspan=2
          = @warning.message
      tr
        td type
        td
          .label class="label-#{@warning.severity}"
            = @warning.type
      - if @warning.url
        tr
          td Reference
          td= link_to @warning.url, @warning.url, :target => "_blank"
      tr
        td file
        td= link_to_if @warning.github_file_path, @warning.path_with_line, @warning.github_file_path, :target => "_blank"
      tr
        td commit
        td= link_to_if @warning.github_commit_path, @warning.sha1, @warning.github_commit_path, :target => "_blank"
      tr
        td commited at
        td= @warning.modified_at
      tr
        td commited by
        td #{@warning.author} (#{@warning.email})
      tr
        td detected at
        td= @warning.report.created_at
      tr
        td report_id
        td= link_to @warning.report_id, @warning.report